### ISSUE TITLE
Guest Reserve Location

### ISSUE THREAD

**Issue by CelticSpice** [CelticSpice/CSC-289#4]
As a guest, I need to be able to reserve, from available reservable locations, a location for some purpose.

**Comment by JGay90** [comment]
this might be a good date picker to use in the reservations will work with this once everything is set up from the recodeing of the gui

https://github.com/LGoodDatePicker/LGoodDatePicker/releases

**Comment by JGay90** [comment]
I think we have decided not to use the Date Picker with the way time is falling now. We have things that work at the moment and that work with the logic we have already
